// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyQb3uXUOEWI8BH37W5RPlLb1HjojrVb8',
    appId: '1:725828416705:android:b8bbeab0e17151ab865040',
    messagingSenderId: '725828416705',
    projectId: 'travel-tailor-cb93a',
    storageBucket: 'travel-tailor-cb93a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZNbj1m1oXawydDihhecLzQErGEBwBSgk',
    appId: '1:725828416705:ios:7eaf7e6cee43bda0865040',
    messagingSenderId: '725828416705',
    projectId: 'travel-tailor-cb93a',
    storageBucket: 'travel-tailor-cb93a.appspot.com',
    iosClientId: '725828416705-2btmp6b642d94vl4qso4h9bdd3bf0obb.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled3445',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCORywFma85Q7H4RPVZFt--OOzvPE7YEeA',
    appId: '1:725828416705:web:3458c52a5cd421d0865040',
    messagingSenderId: '725828416705',
    projectId: 'travel-tailor-cb93a',
    authDomain: 'travel-tailor-cb93a.firebaseapp.com',
    storageBucket: 'travel-tailor-cb93a.appspot.com',
    measurementId: 'G-1BRQMNXTSS',
  );

}